<?php

namespace ContainerYvBCrsu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailer_TransportFactory_PostmarkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailer.transport_factory.postmark' shared service.
     *
     * @return \Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/TransportFactoryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/mailer/Transport/AbstractTransportFactory.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/postmark-mailer/Transport/PostmarkTransportFactory.php';

        return new \Symfony\Component\Mailer\Bridge\Postmark\Transport\PostmarkTransportFactory(($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)), ($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
