<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYvBCrsu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYvBCrsu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYvBCrsu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYvBCrsu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYvBCrsu\App_KernelDevDebugContainer([
    'container.build_hash' => 'YvBCrsu',
    'container.build_id' => 'c6906fb5',
    'container.build_time' => 1719322089,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYvBCrsu');
